"""initial schema

Revision ID: 38e9b9de6628
Revises:
Create Date: 2026-09-09 19:55:56.811512+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("framework", sa.String(length=32), nullable=True),
        sa.Column("task", sa.String(length=48), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("training_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("input_channels", sa.SmallInteger(), nullable=True),
        sa.Column("input_size", sa.Integer(), nullable=True),
        sa.Column("normalization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="uq_model_name_version"),
    )
    op.create_index(
        op.f("ix_model_versions_created_at"), "model_versions", ["created_at"], unique=False
    )
    op.create_index(
        "uq_model_active",
        "model_versions",
        ["name"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "satellite_scenes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("mission", sa.String(length=32), nullable=True),
        sa.Column("platform", sa.String(length=32), nullable=True),
        sa.Column("product_type", sa.String(length=16), nullable=True),
        sa.Column("sensor_mode", sa.String(length=16), nullable=True),
        sa.Column("acquisition_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "footprint",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "bbox",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("polarizations", sa.ARRAY(sa.String(length=4)), nullable=True),
        sa.Column("orbit_direction", sa.String(length=16), nullable=True),
        sa.Column("relative_orbit", sa.Integer(), nullable=True),
        sa.Column("absolute_orbit", sa.Integer(), nullable=True),
        sa.Column("resolution_m", sa.Float(), nullable=True),
        sa.Column("provider_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("download_status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "download_status IN ('NOT_DOWNLOADED', 'DOWNLOADING', 'DOWNLOADED', 'FAILED')",
            name=op.f("ck_satellite_scenes_scenes_download_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_satellite_scenes")),
        sa.UniqueConstraint("product_id", name=op.f("uq_satellite_scenes_product_id")),
    )
    op.create_index(
        "idx_satellite_scenes_bbox",
        "satellite_scenes",
        ["bbox"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_satellite_scenes_footprint",
        "satellite_scenes",
        ["footprint"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_satellite_scenes_acquisition_time"),
        "satellite_scenes",
        ["acquisition_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_satellite_scenes_created_at"), "satellite_scenes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_satellite_scenes_data_provenance"),
        "satellite_scenes",
        ["data_provenance"],
        unique=False,
    )
    op.create_index(
        "ix_scenes_type_time",
        "satellite_scenes",
        ["product_type", "acquisition_time"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('analyst', 'admin')", name=op.f("ck_users_users_role_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_table(
        "vessels",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mmsi", sa.BigInteger(), nullable=False),
        sa.Column("imo", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("callsign", sa.String(length=32), nullable=True),
        sa.Column("ship_type", sa.SmallInteger(), nullable=True),
        sa.Column("ship_type_name", sa.String(length=64), nullable=True),
        sa.Column("flag_country", sa.String(length=80), nullable=True),
        sa.Column("flag_mid", sa.SmallInteger(), nullable=True),
        sa.Column("length_m", sa.Float(), nullable=True),
        sa.Column("width_m", sa.Float(), nullable=True),
        sa.Column("draught_m", sa.Float(), nullable=True),
        sa.Column("destination", sa.String(length=120), nullable=True),
        sa.Column("eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("static_completeness", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "mmsi >= 100000000 AND mmsi <= 999999999", name=op.f("ck_vessels_vessels_mmsi_9_digits")
        ),
        sa.CheckConstraint(
            "static_completeness >= 0 AND static_completeness <= 1",
            name=op.f("ck_vessels_vessels_static_completeness_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vessels")),
        sa.UniqueConstraint("mmsi", name=op.f("uq_vessels_mmsi")),
    )
    op.create_index(op.f("ix_vessels_created_at"), "vessels", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_vessels_data_provenance"), "vessels", ["data_provenance"], unique=False
    )
    op.create_index(op.f("ix_vessels_imo"), "vessels", ["imo"], unique=False)
    op.create_index(op.f("ix_vessels_last_seen"), "vessels", ["last_seen"], unique=False)
    op.create_table(
        "ais_positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vessel_id", sa.UUID(), nullable=False),
        sa.Column("mmsi", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("sog_knots", sa.Float(), nullable=True),
        sa.Column("cog_deg", sa.Float(), nullable=True),
        sa.Column("heading_deg", sa.Float(), nullable=True),
        sa.Column("rot", sa.Float(), nullable=True),
        sa.Column("nav_status", sa.SmallInteger(), nullable=True),
        sa.Column("message_type", sa.String(length=48), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("quality_flags", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cog_deg IS NULL OR (cog_deg >= 0 AND cog_deg < 360)",
            name=op.f("ck_ais_positions_ais_cog_range"),
        ),
        sa.CheckConstraint(
            "heading_deg IS NULL OR (heading_deg >= 0 AND heading_deg < 360)",
            name=op.f("ck_ais_positions_ais_heading_range"),
        ),
        sa.CheckConstraint(
            "sog_knots IS NULL OR (sog_knots >= 0 AND sog_knots < 102.2)",
            name=op.f("ck_ais_positions_ais_sog_plausible"),
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_ais_positions_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ais_positions")),
        sa.UniqueConstraint("mmsi", "timestamp", "source", name="uq_ais_positions_dedup"),
    )
    op.create_index(
        "idx_ais_positions_position",
        "ais_positions",
        ["position"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_ais_timestamp_brin",
        "ais_positions",
        ["timestamp"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_index(
        "ix_ais_valid_time",
        "ais_positions",
        ["timestamp"],
        unique=False,
        postgresql_where=sa.text("is_valid"),
    )
    op.create_index("ix_ais_vessel_time", "ais_positions", ["vessel_id", "timestamp"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_ref", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "aoi",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scenario", sa.String(length=64), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "data_provenance IN ('REAL', 'SYNTHETIC', 'MIXED')",
            name=op.f("ck_cases_cases_provenance_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'ARCHIVED')",
            name=op.f("ck_cases_cases_status_valid"),
        ),
        sa.CheckConstraint("end_time > start_time", name=op.f("ck_cases_cases_time_window_valid")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_cases_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("case_ref", name=op.f("uq_cases_case_ref")),
    )
    op.create_index("idx_cases_aoi", "cases", ["aoi"], unique=False, postgresql_using="gist")
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_data_provenance"), "cases", ["data_provenance"], unique=False)
    op.create_index("ix_cases_owner_created", "cases", ["owner_id", "created_at"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index("ix_cases_time_window", "cases", ["start_time", "end_time"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "case_scenes",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("coverage_fraction", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_scenes_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["satellite_scenes.id"],
            name=op.f("fk_case_scenes_scene_id_satellite_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("case_id", "scene_id", name=op.f("pk_case_scenes")),
    )
    op.create_index(op.f("ix_case_scenes_created_at"), "case_scenes", ["created_at"], unique=False)
    op.create_table(
        "environmental_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("dataset_id", sa.String(length=200), nullable=True),
        sa.Column("variables", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "extent",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("grid_resolution_deg", sa.Float(), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.Column(
            "run_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_environmental_runs_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environmental_runs")),
    )
    op.create_index(
        "idx_environmental_runs_extent",
        "environmental_runs",
        ["extent"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_env_case_time", "environmental_runs", ["case_id", "time_start"], unique=False
    )
    op.create_index(
        op.f("ix_environmental_runs_created_at"), "environmental_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_environmental_runs_data_provenance"),
        "environmental_runs",
        ["data_provenance"],
        unique=False,
    )
    op.create_table(
        "evidence_artifacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("artifact_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("related_table", sa.String(length=64), nullable=True),
        sa.Column("related_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "artifact_type IN ('GRD', 'TILE', 'PROBABILITY_RASTER', 'MASK', 'ENV_NETCDF', 'DRIFT_OUTPUT', 'DENSITY_GRID', 'REPORT_HTML', 'REPORT_PDF', 'GEOJSON')",
            name=op.f("ck_evidence_artifacts_artifacts_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_evidence_artifacts_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_artifacts")),
    )
    op.create_index(
        "ix_artifacts_case_type", "evidence_artifacts", ["case_id", "artifact_type"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_artifacts_checksum_sha256"),
        "evidence_artifacts",
        ["checksum_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_artifacts_created_at"), "evidence_artifacts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_artifacts_data_provenance"),
        "evidence_artifacts",
        ["data_provenance"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("pipeline_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("step", sa.String(length=200), nullable=True),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("attempt", sa.SmallInteger(), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("depends_on", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_jobs_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_jobs_jobs_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_jobs_case_id_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_case_created", "jobs", ["case_id", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index("ix_jobs_dispatch", "jobs", ["status", "priority", "queued_at"], unique=False)
    op.create_index(op.f("ix_jobs_pipeline_id"), "jobs", ["pipeline_id"], unique=False)
    op.create_index(
        "ix_jobs_running_heartbeat",
        "jobs",
        ["heartbeat_at"],
        unique=False,
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_table(
        "spill_detections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("perimeter_km", sa.Float(), nullable=True),
        sa.Column("detection_confidence", sa.Float(), nullable=False),
        sa.Column("mean_probability", sa.Float(), nullable=True),
        sa.Column("max_probability", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.Column("probability_raster_uri", sa.Text(), nullable=True),
        sa.Column("mask_raster_uri", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.Column(
            "run_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "area_km2 >= 0", name=op.f("ck_spill_detections_detections_area_non_negative")
        ),
        sa.CheckConstraint(
            "detection_confidence >= 0 AND detection_confidence <= 1",
            name=op.f("ck_spill_detections_detections_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_spill_detections_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_spill_detections_model_version_id_model_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["satellite_scenes.id"],
            name=op.f("fk_spill_detections_scene_id_satellite_scenes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spill_detections")),
    )
    op.create_index(
        "idx_spill_detections_centroid",
        "spill_detections",
        ["centroid"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_spill_detections_geometry",
        "spill_detections",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_detections_case_time", "spill_detections", ["case_id", "detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_spill_detections_created_at"), "spill_detections", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_spill_detections_data_provenance"),
        "spill_detections",
        ["data_provenance"],
        unique=False,
    )
    op.create_table(
        "trajectories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("vessel_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("position_count", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("mean_sog_knots", sa.Float(), nullable=True),
        sa.Column("max_sog_knots", sa.Float(), nullable=True),
        sa.Column("gap_count", sa.Integer(), nullable=False),
        sa.Column("max_gap_minutes", sa.Float(), nullable=False),
        sa.Column("total_gap_minutes", sa.Float(), nullable=False),
        sa.Column("coverage_ratio", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("quality_flags", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1",
            name=op.f("ck_trajectories_trajectories_quality_range"),
        ),
        sa.CheckConstraint(
            "time_end >= time_start", name=op.f("ck_trajectories_trajectories_time_order")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_trajectories_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_trajectories_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trajectories")),
    )
    op.create_index(
        "idx_trajectories_geometry",
        "trajectories",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(op.f("ix_trajectories_case_id"), "trajectories", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_trajectories_created_at"), "trajectories", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_trajectories_data_provenance"), "trajectories", ["data_provenance"], unique=False
    )
    op.create_index(
        "ix_trajectories_vessel_time", "trajectories", ["vessel_id", "time_start"], unique=False
    )
    op.create_table(
        "drift_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("spill_id", sa.UUID(), nullable=False),
        sa.Column("environmental_run_id", sa.UUID(), nullable=True),
        sa.Column("engine", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("number_of_particles", sa.Integer(), nullable=False),
        sa.Column("ensemble_members", sa.Integer(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("time_step_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "origin_geometry",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("origin_confidence", sa.Float(), nullable=True),
        sa.Column("density_grid_uri", sa.Text(), nullable=True),
        sa.Column("contours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inferred_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inferred_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.Column(
            "run_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "engine IN ('openoil', 'opendrift', 'analytical')",
            name=op.f("ck_drift_runs_drift_engine_valid"),
        ),
        sa.CheckConstraint(
            "mode IN ('FORWARD', 'BACKWARD', 'ENSEMBLE')",
            name=op.f("ck_drift_runs_drift_mode_valid"),
        ),
        sa.CheckConstraint(
            "number_of_particles > 0", name=op.f("ck_drift_runs_drift_particles_positive")
        ),
        sa.CheckConstraint(
            "origin_confidence IS NULL OR (origin_confidence >= 0 AND origin_confidence <= 1)",
            name=op.f("ck_drift_runs_drift_origin_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_drift_runs_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["environmental_run_id"],
            ["environmental_runs.id"],
            name=op.f("fk_drift_runs_environmental_run_id_environmental_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spill_id"],
            ["spill_detections.id"],
            name=op.f("fk_drift_runs_spill_id_spill_detections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_runs")),
    )
    op.create_index(
        "idx_drift_runs_origin_geometry",
        "drift_runs",
        ["origin_geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("ix_drift_case_created", "drift_runs", ["case_id", "created_at"], unique=False)
    op.create_index(op.f("ix_drift_runs_created_at"), "drift_runs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_drift_runs_data_provenance"), "drift_runs", ["data_provenance"], unique=False
    )
    op.create_index("ix_drift_spill_mode", "drift_runs", ["spill_id", "mode"], unique=False)
    op.create_table(
        "verification_results",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("spill_id", sa.UUID(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verification_confidence", sa.Float(), nullable=False),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("wind_source", sa.String(length=64), nullable=True),
        sa.Column("shape_area_km2", sa.Float(), nullable=True),
        sa.Column("shape_perimeter_km", sa.Float(), nullable=True),
        sa.Column("shape_complexity", sa.Float(), nullable=True),
        sa.Column("shape_compactness", sa.Float(), nullable=True),
        sa.Column("shape_elongation", sa.Float(), nullable=True),
        sa.Column("slick_mean_db", sa.Float(), nullable=True),
        sa.Column("background_mean_db", sa.Float(), nullable=True),
        sa.Column("contrast_db", sa.Float(), nullable=True),
        sa.Column("slick_std_db", sa.Float(), nullable=True),
        sa.Column("background_std_db", sa.Float(), nullable=True),
        sa.Column("gradient_mean", sa.Float(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("classifier_name", sa.String(length=64), nullable=True),
        sa.Column("classifier_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "run_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED', 'UNCERTAIN', 'FALSE_POSITIVE')",
            name=op.f("ck_verification_results_verification_status_valid"),
        ),
        sa.CheckConstraint(
            "verification_confidence >= 0 AND verification_confidence <= 1",
            name=op.f("ck_verification_results_verification_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["spill_id"],
            ["spill_detections.id"],
            name=op.f("fk_verification_results_spill_id_spill_detections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
    )
    op.create_index(
        op.f("ix_verification_results_created_at"),
        "verification_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "uq_verification_latest",
        "verification_results",
        ["spill_id"],
        unique=True,
        postgresql_where=sa.text("is_latest"),
    )
    op.create_table(
        "attributions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("spill_id", sa.UUID(), nullable=False),
        sa.Column("drift_run_id", sa.UUID(), nullable=True),
        sa.Column("vessel_id", sa.UUID(), nullable=False),
        sa.Column("trajectory_id", sa.UUID(), nullable=True),
        sa.Column("origin_proximity", sa.Float(), nullable=False),
        sa.Column("time_match", sa.Float(), nullable=False),
        sa.Column("trajectory_match", sa.Float(), nullable=False),
        sa.Column("heading_match", sa.Float(), nullable=False),
        sa.Column("speed_match", sa.Float(), nullable=False),
        sa.Column("ais_reliability", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("factor_explanations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("closest_approach_km", sa.Float(), nullable=True),
        sa.Column("closest_approach_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scoring_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.Column(
            "run_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ais_reliability >= 0 AND ais_reliability <= 1",
            name=op.f("ck_attributions_attribution_ais_reliability_range"),
        ),
        sa.CheckConstraint(
            "final_score >= 0 AND final_score <= 1",
            name=op.f("ck_attributions_attribution_final_score_range"),
        ),
        sa.CheckConstraint(
            "heading_match >= 0 AND heading_match <= 1",
            name=op.f("ck_attributions_attribution_heading_match_range"),
        ),
        sa.CheckConstraint(
            "origin_proximity >= 0 AND origin_proximity <= 1",
            name=op.f("ck_attributions_attribution_origin_proximity_range"),
        ),
        sa.CheckConstraint(
            "speed_match >= 0 AND speed_match <= 1",
            name=op.f("ck_attributions_attribution_speed_match_range"),
        ),
        sa.CheckConstraint(
            "time_match >= 0 AND time_match <= 1",
            name=op.f("ck_attributions_attribution_time_match_range"),
        ),
        sa.CheckConstraint(
            "trajectory_match >= 0 AND trajectory_match <= 1",
            name=op.f("ck_attributions_attribution_trajectory_match_range"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_attributions_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["drift_run_id"],
            ["drift_runs.id"],
            name=op.f("fk_attributions_drift_run_id_drift_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spill_id"],
            ["spill_detections.id"],
            name=op.f("fk_attributions_spill_id_spill_detections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trajectory_id"],
            ["trajectories.id"],
            name=op.f("fk_attributions_trajectory_id_trajectories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_attributions_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributions")),
        sa.UniqueConstraint(
            "case_id", "spill_id", "vessel_id", "scoring_version", name="uq_attribution_unique"
        ),
    )
    op.create_index(
        op.f("ix_attributions_created_at"), "attributions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_attributions_data_provenance"), "attributions", ["data_provenance"], unique=False
    )
    op.create_index(
        "ix_attributions_rank", "attributions", ["case_id", "spill_id", "rank"], unique=False
    )
    op.create_table(
        "drift_particles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("drift_run_id", sa.UUID(), nullable=False),
        sa.Column("particle_id", sa.Integer(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("member", sa.SmallInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                spatial_index=False,
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), nullable=True),
        sa.Column("mass_oil", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["drift_run_id"],
            ["drift_runs.id"],
            name=op.f("fk_drift_particles_drift_run_id_drift_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_particles")),
    )
    op.create_index(
        "idx_drift_particles_position",
        "drift_particles",
        ["position"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_particles_run_step", "drift_particles", ["drift_run_id", "step_index"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_particles_run_step", table_name="drift_particles")
    op.drop_index(
        "idx_drift_particles_position", table_name="drift_particles", postgresql_using="gist"
    )
    op.drop_table("drift_particles")
    op.drop_index("ix_attributions_rank", table_name="attributions")
    op.drop_index(op.f("ix_attributions_data_provenance"), table_name="attributions")
    op.drop_index(op.f("ix_attributions_created_at"), table_name="attributions")
    op.drop_table("attributions")
    op.drop_index(
        "uq_verification_latest",
        table_name="verification_results",
        postgresql_where=sa.text("is_latest"),
    )
    op.drop_index(op.f("ix_verification_results_created_at"), table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_index("ix_drift_spill_mode", table_name="drift_runs")
    op.drop_index(op.f("ix_drift_runs_data_provenance"), table_name="drift_runs")
    op.drop_index(op.f("ix_drift_runs_created_at"), table_name="drift_runs")
    op.drop_index("ix_drift_case_created", table_name="drift_runs")
    op.drop_index(
        "idx_drift_runs_origin_geometry", table_name="drift_runs", postgresql_using="gist"
    )
    op.drop_table("drift_runs")
    op.drop_index("ix_trajectories_vessel_time", table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_data_provenance"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_created_at"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_case_id"), table_name="trajectories")
    op.drop_index("idx_trajectories_geometry", table_name="trajectories", postgresql_using="gist")
    op.drop_table("trajectories")
    op.drop_index(op.f("ix_spill_detections_data_provenance"), table_name="spill_detections")
    op.drop_index(op.f("ix_spill_detections_created_at"), table_name="spill_detections")
    op.drop_index("ix_detections_case_time", table_name="spill_detections")
    op.drop_index(
        "idx_spill_detections_geometry", table_name="spill_detections", postgresql_using="gist"
    )
    op.drop_index(
        "idx_spill_detections_centroid", table_name="spill_detections", postgresql_using="gist"
    )
    op.drop_table("spill_detections")
    op.drop_index(
        "ix_jobs_running_heartbeat",
        table_name="jobs",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.drop_index(op.f("ix_jobs_pipeline_id"), table_name="jobs")
    op.drop_index("ix_jobs_dispatch", table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index("ix_jobs_case_created", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_evidence_artifacts_data_provenance"), table_name="evidence_artifacts")
    op.drop_index(op.f("ix_evidence_artifacts_created_at"), table_name="evidence_artifacts")
    op.drop_index(op.f("ix_evidence_artifacts_checksum_sha256"), table_name="evidence_artifacts")
    op.drop_index("ix_artifacts_case_type", table_name="evidence_artifacts")
    op.drop_table("evidence_artifacts")
    op.drop_index(op.f("ix_environmental_runs_data_provenance"), table_name="environmental_runs")
    op.drop_index(op.f("ix_environmental_runs_created_at"), table_name="environmental_runs")
    op.drop_index("ix_env_case_time", table_name="environmental_runs")
    op.drop_index(
        "idx_environmental_runs_extent", table_name="environmental_runs", postgresql_using="gist"
    )
    op.drop_table("environmental_runs")
    op.drop_index(op.f("ix_case_scenes_created_at"), table_name="case_scenes")
    op.drop_table("case_scenes")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_cases_time_window", table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index("ix_cases_owner_created", table_name="cases")
    op.drop_index(op.f("ix_cases_data_provenance"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_index("idx_cases_aoi", table_name="cases", postgresql_using="gist")
    op.drop_table("cases")
    op.drop_index("ix_ais_vessel_time", table_name="ais_positions")
    op.drop_index(
        "ix_ais_valid_time", table_name="ais_positions", postgresql_where=sa.text("is_valid")
    )
    op.drop_index("ix_ais_timestamp_brin", table_name="ais_positions", postgresql_using="brin")
    op.drop_index("idx_ais_positions_position", table_name="ais_positions", postgresql_using="gist")
    op.drop_table("ais_positions")
    op.drop_index(op.f("ix_vessels_last_seen"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_imo"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_data_provenance"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_created_at"), table_name="vessels")
    op.drop_table("vessels")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_scenes_type_time", table_name="satellite_scenes")
    op.drop_index(op.f("ix_satellite_scenes_data_provenance"), table_name="satellite_scenes")
    op.drop_index(op.f("ix_satellite_scenes_created_at"), table_name="satellite_scenes")
    op.drop_index(op.f("ix_satellite_scenes_acquisition_time"), table_name="satellite_scenes")
    op.drop_index(
        "idx_satellite_scenes_footprint", table_name="satellite_scenes", postgresql_using="gist"
    )
    op.drop_index(
        "idx_satellite_scenes_bbox", table_name="satellite_scenes", postgresql_using="gist"
    )
    op.drop_table("satellite_scenes")
    op.drop_index(
        "uq_model_active", table_name="model_versions", postgresql_where=sa.text("is_active")
    )
    op.drop_index(op.f("ix_model_versions_created_at"), table_name="model_versions")
    op.drop_table("model_versions")
    # ### end Alembic commands ###
