'use client';

import { useId, useRef, useState } from 'react';
import { IconSparkle } from '@/components/ui/Icons';
import type { Attribution } from '@/lib/api/types';
import { plainLanguageSummary } from '@/lib/insights';
import { gsap, prefersReducedMotion, useGSAP } from '@/lib/motion/gsap';
import styles from './explain.module.css';

export interface PlainLanguageSummaryProps {
  attribution: Attribution;
  /** Every candidate in the same ranking — needed for "ranked 2nd of 6". */
  all: readonly Attribution[];
}

/**
 * "Explain in plain English" — a reading of one candidate's score for a
 * non-specialist (a magistrate, a journalist, a judge at a demo).
 *
 * It is generated by fixed rules from the factor data the server returned, not
 * by a language model, and it says so: it cannot hallucinate a fact because it
 * only restates numbers already on the screen, in the product's own careful
 * vocabulary (see `plainLanguageSummary`).
 */
export function PlainLanguageSummary({ attribution, all }: PlainLanguageSummaryProps) {
  const [open, setOpen] = useState(false);
  const panelId = useId();
  const ref = useRef<HTMLDivElement | null>(null);
  const sentences = plainLanguageSummary(attribution, all);

  useGSAP(
    () => {
      if (!open || prefersReducedMotion()) return;
      const lines = ref.current?.querySelectorAll('[data-sentence]');
      if (!lines?.length) return;
      gsap.fromTo(
        lines,
        { autoAlpha: 0, y: 8, clipPath: 'inset(0 100% 0 0)' },
        {
          autoAlpha: 1,
          y: 0,
          clipPath: 'inset(0 0% 0 0)',
          duration: 0.9,
          stagger: 0.28,
          ease: 'power2.out',
          clearProps: 'clipPath',
        },
      );
    },
    { scope: ref, dependencies: [open] },
  );

  return (
    <div className={styles.root}>
      <button
        type="button"
        className={styles.trigger}
        aria-expanded={open}
        aria-controls={panelId}
        onClick={() => setOpen((value) => !value)}
      >
        <span className={styles.triggerIcon}>
          <IconSparkle size={15} />
        </span>
        {open ? 'Hide the plain-English reading' : 'Explain this in plain English'}
      </button>

      {open ? (
        <div className={styles.panel} id={panelId} ref={ref}>
          <ol className={styles.sentences}>
            {sentences.map((sentence) => (
              <li key={sentence} data-sentence="">
                {sentence}
              </li>
            ))}
          </ol>
          <p className={styles.provenance}>
            Written from the factor data above by fixed rules — not by a language model — so it adds
            no fact the data does not contain.
          </p>
        </div>
      ) : null}
    </div>
  );
}
